### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by veetack1** [bivashy/MC-Auth-with-Link#173]
**Describe the bug**
Буду писать на родном языке чтобы без проблем, недавно столкнулся с багом Время вышло! Попробуйте снова. Время на авторизацию у игроков стоит 250 секунд, некоторые аккаунты при входе выкидывает сразу с такой ошибкой, при этом в консоли пусто и ошибок нет, есть варианты что можно сделать?

https://youtube.com/shorts/24zH-4Y9Mbs?feature=share
upd: прокси velocity

**Comment by bivashy** [comment]
https://github.com/bivashy/MC-Auth-with-Link/issues/140

Duplicate, use latest build.
