### ISSUE TITLE
add ssl support

### ISSUE THREAD

**Issue by Playsus1234** [bivashy/MC-Auth-with-Link#177]
add ssl support

**Comment by bivashy** [comment]
How exactly this should be implemented? Where SSL should be added? How user could use SSL?

**Comment by Playsus1234** [comment]
Mariadb supports the ssl feature.

**Comment by bivashy** [comment]
You should define `ssl` using `config.yml`:
https://github.com/bivashy/MC-Auth-with-Link/blob/5d4f33d25ae7441d325e522a22a218ca25f3f9e2/core/src/main/resources/configurations/config.yml#L19-L23
Replacing your `url` section into string:
`jdbc:mariadb://HOST:3306/DATABASE?useSsl=true`
YOU SHOULD BE AWARE THAT SSL SHOULD BE ENABLED ON SERVER SIDE TOO! [[1]](https://mariadb.com/kb/en/using-tls-ssl-with-mariadb-java-connector/)

Used resources: 
1. https://mariadb.com/kb/en/using-tls-ssl-with-mariadb-java-connector/
2. https://github.com/bivashy/MC-Auth-with-Link/blob/main/core/src/main/resources/configurations/config.yml
