### ISSUE TITLE
add maximum-lifetime

### ISSUE THREAD

**Issue by Playsus1234** [bivashy/MC-Auth-with-Link#178]
add maximum-lifetime

**Comment by bivashy** [comment]
Hello there, seems like that you're opening issues without any useful description.
You should add description that will explain what you want, else issues will be marked as spam, because i've no clue where i should add 'maximum-lifetime'

**Comment by Playsus1234** [comment]
wait_timeout mariadb

**Comment by bivashy** [comment]
Duplicate: https://github.com/bivashy/MC-Auth-with-Link/issues/177#issuecomment-2156429881
