### ISSUE TITLE
I need help with linking additional protection

### ISSUE THREAD

**Issue by krevkut** [bivashy/MC-Auth-with-Link#180]
**Describe the bug**
after my computer accidentally turned off, linking accounts to vk stopped working. Before this, everything worked, I even updated the plugin to a new version, deleted the old cfg, but it didn’t help

**To Reproduce**
1. I write /addvk in chat
2. I get the code and enter it into the VK bot
3. The bot writes to me that everything is connected, but it’s not like that, it doesn’t see that I’ve linked it.

**Expected behavior**

**Screenshots**
I want to find out what’s wrong, because before the shutdown everything worked perfectly

**Additional context**
This is what it says to me when I enter this:
![image](https://github.com/bivashy/MC-Auth-with-Link/assets/130036854/d53c6e7e-12a5-4abe-a7ff-2ace33adeb76)

**Comment by bivashy** [comment]
1. Plugin version
2. Platform (Velocity / BungeeCord)

**Comment by krevkut** [comment]
1. 1.7.12
2. Velocity
3. This?
![image](https://github.com/bivashy/MC-Auth-with-Link/assets/130036854/18f0b119-529b-48cb-85b8-5659573b4c30)


> 1. Plugin version
> 2. Platform (Velocity / BungeeCord)
> 3. How Database row where player_name="YOUR_NAME" looks like



> 1. Версия плагина
> 2. Платформа (Velocity / BungeeCord)
> 3. Как выглядит строка базы данных, где player_name="ВАШЕ_ИМЯ"

1.

**Comment by bivashy** [comment]
> 1. 1.7.12
> 
>     2. Velocity
> 
>     3. This?
>        ![image](https://private-user-images.githubusercontent.com/130036854/341013268-18f0b119-529b-48cb-85b8-5659573b4c30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTc5NDMsIm5iZiI6MTcxODc5NzY0MywicGF0aCI6Ii8xMzAwMzY4NTQvMzQxMDEzMjY4LTE4ZjBiMTE5LTUyOWItNDhjYi04NWI4LTU2NTk1NzNiNGMzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQxMTQ3MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjIwMjFkZjI5ODFhMjUyMDU4ZWRlNWIwOWRmYzQ2YjI1ODkzMWRiODYyZjY5MTFhZGE5NDg5ZTFmNmM0NTNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SkIbXOceuei92I4KLClzizoZAgRvC-xMWo27horFf9Y)
> 
> 
> > 1. Plugin version
> > 2. Platform (Velocity / BungeeCord)
> > 3. How Database row where player_name="YOUR_NAME" looks like
> 
> > 1. Версия плагина
> > 2. Платформа (Velocity / BungeeCord)
> > 3. Как выглядит строка базы данных, где player_name="ВАШЕ_ИМЯ"

You are using legacy version of this plugin. Please consider downloading dev build/beta version

**Comment by krevkut** [comment]
Thanks for the help, but I solved it differently: 
I had to delete auth-links in the Table database, after that everything worked
