### ISSUE TITLE
[Bug] Error message in console

### ISSUE THREAD

**Issue by remix2021687** [bivashy/MC-Auth-with-Link#211]
**Describe the bug**
Error loading a class

**To Reproduce**
1. Start Server
2. See error on screenshot

**Expected behavior**
Everything works, but this error confuses me

**Screenshots**
![image](https://github.com/user-attachments/assets/cbe55b92-8236-4293-a6fc-7765ed88aa58)

**Comment by bivashy** [comment]
This is not an error, it is a warning that some libraries (JDA) will not be logged.

**Comment by remix2021687** [comment]
> This is not an error, it is a warning that some libraries (JDA) will not be logged.

Yeah, I got it, I just thought it said error. Thanks.

**Comment by bivashy** [comment]
> Download https://HIDDEN/file password: changeme In the installer menu, select "gcc."

Reported. Do not follow that link, totally unrelated to the issuet
