### ISSUE TITLE
1.19.3 PurPur не загружается

### ISSUE THREAD

**Issue by MuTBu** [bivashy/MC-Auth-with-Link#33]
Предоставляю часть лога с ошибкой и скриншот с консоли. VK API и TG API успешно загружаются

[Новый текстовый документ.txt](https://github.com/bivashy/MC-Auth-with-Link/files/11070739/default.txt)

![изображение](https://user-images.githubusercontent.com/66108320/227754390-7c5abdb2-b090-48b5-b53c-58b2c03d8d00.png)

**Comment by bivashy** [comment]
Плагин для BungeeCord/Velocity. Закрываю тему. 

Plugin for BungeeCord/Velocity. Closing.
