### ISSUE TITLE
[Suggestion] Discord support

### ISSUE THREAD

**Issue by bivashy** [bivashy/MC-Auth-with-Link#41]
We should have these functions:
- [x] Plugin will give/remove role (_optionally with permissions_) when linked. (*Configurable*)
- [x] Link from channel in guild or in bot private messages. (*~Configurable~*)
- [x] Discord Command API support. (*Configurable*)

**Comment by NoPlagiarism** [comment]
Update ReadMe pls

- Requirements
- MultiFactor auth (Just add Discord)



- Also, it would be nice, if you added link to plugin page on Spigot
