### ISSUE TITLE
[bug] The VK and Telegram bots are death after some time

### ISSUE THREAD

**Issue by stngularity** [bivashy/MC-Auth-with-Link#54]
Hello, I'm involved in the technical side of some server, and I (along with the players of the server) discovered a problem related to telegram and VK bots. After some time of plugin work, they simply stop responding to commands and buttons at messages. Because of what, players can not authorize in their account.

**Comment by bivashy** [comment]
Hello. I need more information, because i cannot replicate it. Maybe you have stacktraces in your console? 
Also this may be issue with your network

**Comment by bivashy** [comment]
@stngularity

**Comment by stngularity** [comment]
Sorry, I'm not at home right now and I can't see the logs. When I can, I'll let you know.

**Comment by stngularity** [comment]
Okay, perhaps the problem was in the server (well, which host), no more such problems with bots.
