### ISSUE TITLE
NullPointerException and other "not enough arguments" handling issues while using Telegram bot

### ISSUE THREAD

**Issue by arskvsh** [bivashy/MC-Auth-with-Link#72]
**MCAuth 1.7.12, TelegramBotApi 1.0.0, Velocity-3.2.0-SNAPSHOT-265**

_I refer to the commands with their config names as I have the slash commands renamed. Config attached: [telegram-config.yml.txt](https://github.com/bivashy/MC-Auth-with-Link/files/12772753/telegram-config.yml.txt)_

Using 'account-control' and 'unlink' (and may be some other?) commands without parameters in the Telegram bot causes NullPointerException in the server console (server doesn't crash though). Seems that it should be handled at least as 'change-pass' one, which neither throws any exceptions nor returning any messages in Telegram when used without parameters.

However, both behaviours seem strange as there are messages that are supposed to be shown in such cases, their translations can be seen in the config (changepass-not-enough-arguments, unlink-not-enough-arguments, etc.). I haven't succeeded getting those messages anyhow.

![image](https://github.com/bivashy/MC-Auth-with-Link/assets/65048730/99a31d0f-c3ec-45ec-b1cf-70c3a280e350)
```
[01:22:53 ERROR]: java.lang.NullPointerException: Cannot invoke "com.bivashy.auth.api.account.Account.getName()" because "account" is null
[01:22:53 ERROR]:       at me.mastercapexd.auth.messenger.commands.AccountCommand.accountMenu(AccountCommand.java:18)
```
![image](https://github.com/bivashy/MC-Auth-with-Link/assets/65048730/357c4788-a20b-4c50-8435-498d4c71e837)

**Comment by bivashy** [comment]
Thank you for providing such a thorough issue report. This would be fixed in the next update.

Issue appears to lie within the command library, which interprets certain arguments as "null", resulting in the disregarding of certain messages.

**Comment by bivashy** [comment]
Fix seems to be working
![изображение](https://github.com/bivashy/MC-Auth-with-Link/assets/85439143/d2feb731-007f-43aa-bf95-fd81366ddf9f)
