### ISSUE TITLE
[Suggestion] Bypass max linked accounts count for administrators

### ISSUE THREAD

**Issue by arskvsh** [bivashy/MC-Auth-with-Link#77]
It would be cool if we had an opportunity to link any number of accounts to the Telegram, if the TG account ID is listed in the admins list in the config.

Seems that this should be an important part of the future [blocking of unregistered users feature](https://github.com/bivashy/MC-Auth-with-Link/issues/18) as it would make test/admin game-only accounts impossible, however, I suppose that the bypass can be implemented way earlier.

**Comment by bivashy** [comment]
Thanks for bringing this up! The implementation seems feasible. I'll look into it when I have some spare time.

In the meantime, the issue will remain open. Anyone interested in contributing can submit a pull request for this feature.
