### ISSUE TITLE
Добавить задержку команды /changepassword

### ISSUE THREAD

**Issue by SosisonReloaded** [bivashy/MC-Auth-with-Link#92]
Добавить задержку команды /changepassword
При очень частой смене пароля нагружается процессор из-за чего выключается велосити/банджикорд
предлагаю добавить задержку команды /changepassword что-бы не выключали сервер злоумышленники данной уязвимостью

**Comment by scar-day** [comment]
она есть

**Comment by SosisonReloaded** [comment]
нету в последней версии плагина которая в релизе

**Comment by scar-day** [comment]
в релизе нет, но на гитхабе во вкладке Actions релиз с этой задержкой есть

**Comment by bivashy** [comment]
Already done #68
